input_boolean:
  wattwise_battery_charging_from_grid:
    name: WattWise Battery Charging from Grid
    icon: mdi:battery-charging
  wattwise_battery_discharging_enabled:
    name: WattWise Battery Discharging Enabled
    icon: mdi:battery-minus
  wattwise_manual_optimization:
    name: WattWise Manual Optimization Trigger
    icon: mdi:play

automation:
  - alias: Trigger WattWise Manual Optimization
    description: Fires MANUAL_BATTERY_OPTIMIZATION event when turned on
    triggers:
      - entity_id: input_boolean.wattwise_manual_optimization
        to: "on"
        trigger: state
    conditions: []
    actions:
      - event: MANUAL_BATTERY_OPTIMIZATION
      - target:
          entity_id: input_boolean.wattwise_manual_optimization
        action: input_boolean.turn_off
        data: {}
    mode: single

sensor:
  - platform: rest
    unique_id: wattwise_tibber_prices
    name: Wattwise Tibber Prices
    resource: https://api.tibber.com/v1-beta/gql
    method: POST
    payload: '{ "query": "{ viewer { homes { currentSubscription { status priceInfo { current { total level } today { total level } tomorrow { total level } } } } } }" }'
    json_attributes_path: "$.data.viewer.homes[0].currentSubscription.priceInfo"
    json_attributes:
      - today
      - tomorrow
    value_template: "{{ value_json.data.viewer.homes[0].currentSubscription.priceInfo.current.total | float }}"
    scan_interval: 30
    headers:
      Authorization: !secret tibber_token
      Content-Type: application/json
      User-Agent: REST
    unit_of_measurement: EUR/kWh

template:
  - sensor:
      - name: "WattWise Battery Charge from Solar"
        unique_id: "wattwise_battery_charge_from_solar"
        unit_of_measurement: "kW"
        state_class: "measurement"
        device_class: "power"
        icon: "mdi:solar-power"
        state: "{{ 0 }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Battery Charge from Grid"
        unique_id: "wattwise_battery_charge_from_grid"
        unit_of_measurement: "kW"
        state_class: "measurement"
        device_class: "power"
        icon: "mdi:transmission-tower"
        state: "{{ 0 }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Battery Discharge"
        unique_id: "wattwise_battery_discharge"
        unit_of_measurement: "kW"
        state_class: "measurement"
        device_class: "power"
        icon: "mdi:battery-outline"
        state: "{{ 0 }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Maximum Discharge Possible"
        unique_id: "wattwise_maximum_discharge_possible"
        unit_of_measurement: "kW"
        state_class: "measurement"
        device_class: "power"
        icon: "mdi:battery-minus-outline"
        state: "{{ 0 }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Grid Export"
        unique_id: "wattwise_grid_export"
        unit_of_measurement: "kW"
        state_class: "measurement"
        device_class: "power"
        icon: "mdi:export"
        state: "{{ 0 }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Grid Import"
        unique_id: "wattwise_grid_import"
        unit_of_measurement: "kW"
        state_class: "measurement"
        device_class: "power"
        icon: "mdi:import"
        state: "{{ 0 }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise State of Charge"
        unique_id: "wattwise_state_of_charge"
        unit_of_measurement: "kWh"
        state_class: "measurement"
        device_class: "battery"
        icon: "mdi:battery"
        state: "{{ 0 }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise State of Charge (%)"
        unique_id: "wattwise_state_of_charge_percentage"
        unit_of_measurement: "%"
        state_class: "measurement"
        device_class: "battery"
        icon: "mdi:battery"
        state: "{{ 0 }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Consumption Forecast"
        unique_id: "wattwise_consumption_forecast"
        unit_of_measurement: "kW"
        state_class: "measurement"
        device_class: "power"
        icon: "mdi:home"
        state: "{{ 0 }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Solar Production Forecast"
        unique_id: "wattwise_solar_production_forecast"
        unit_of_measurement: "kW"
        state_class: "measurement"
        device_class: "power"
        icon: "mdi:weather-sunny"
        state: "{{ 0 }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Forecast Horizon"
        unique_id: "wattwise_forecast_horizon"
        unit_of_measurement: "h"
        state_class: "measurement"
        icon: "mdi:clock"
        state: "{{ 0 }}"

  - binary_sensor:
      - name: "WattWise Battery Charging from Grid"
        unique_id: "wattwise_battery_charging_from_grid"
        device_class: power
        icon: "mdi:battery-charging"
        state: "{{ off }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Battery Discharging Enabled"
        unique_id: "wattwise_battery_discharging_enabled"
        device_class: power
        icon: "mdi:battery-minus"
        state: "{{ off }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Battery Full Charge Status"
        unique_id: "wattwise_battery_full_charge_status"
        icon: "mdi:battery-charging-100"
        state: "{{ 0 }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Within cheapest hour"
        unique_id: "wattwise_within_cheapest_hour"
        icon: "mdi:clock-time-one-outline"
        state: "{{ off }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Within cheapest 2 hours"
        unique_id: "wattwise_within_cheapest_2_hours"
        icon: "mdi:clock-time-two-outline"
        state: "{{ off }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Within cheapest 3 hours"
        unique_id: "wattwise_within_cheapest_3_hours"
        icon: "mdi:clock-time-three-outline"
        state: "{{ off }}"
        attributes:
          forecast: "{{ [] }}"
