input_boolean:
  wattwise_battery_charging_from_grid:
    name: WattWise Battery Charging from Grid
    icon: mdi:battery-charging
  wattwise_battery_discharging_enabled:
    name: WattWise Battery Discharging Enabled
    icon: mdi:battery-minus
  wattwise_manual_optimization:
    name: WattWise Manual Optimization Trigger
    icon: mdi:play

automation:
  - alias: Trigger WattWise Manual Optimization
    description: Fires MANUAL_BATTERY_OPTIMIZATION event when turned on
    triggers:
      - entity_id: input_boolean.wattwise_manual_optimization
        to: "on"
        trigger: state
    conditions: []
    actions:
      - event: MANUAL_BATTERY_OPTIMIZATION
      - target:
          entity_id: input_boolean.wattwise_manual_optimization
        action: input_boolean.turn_off
        data: {}
    mode: single

template:
  - sensor:
      - name: "Wattwise Tibber Prices"
        unique_id: "wattwise_tibber_prices"
        state: >
          {% set ns = namespace(price='unknown') %}
          {% set prices = state_attr('sensor.average_electricity_price', 'prices_today') %}
          {% set idx = ((now().hour) % 24) %}
          {% if prices and prices[idx] is defined %}
            {% set ns.price = prices[idx].price | float | round(4) %}
          {% endif %}
          {{ ns.price }}
        attributes:
          today: >
            {% set avg = states('sensor.average_electricity_price') | float(0) %}
            {% set prices = state_attr('sensor.average_electricity_price', 'prices_today') %}
            {% set ns = namespace(result=[]) %}
            {% for item in prices %}
              {% set price = item.get('price') %}
              {% if price is not none and avg > 0 %}
                {% set pct = (price / avg * 100) | float(0) %}
                {% if pct < 60 %}
                  {% set level = 'VERY_CHEAP' %}
                {% elif pct <= 90 %}
                  {% set level = 'CHEAP' %}
                {% elif pct < 115 %}
                  {% set level = 'NORMAL' %}
                {% elif pct < 140 %}
                  {% set level = 'EXPENSIVE' %}
                {% else %}
                  {% set level = 'VERY_EXPENSIVE' %}
                {% endif %}
                {% set entry = {'total': price | round(4), 'level': level} %}
                {% set ns.result = ns.result + [entry] %}
              {% endif %}
            {% endfor %}
            {{ ns.result }}
          tomorrow: >
            {% set avg = states('sensor.average_electricity_price') | float(0) %}
            {% set prices = state_attr('sensor.average_electricity_price', 'prices_tomorrow') %}
            {% set ns = namespace(result=[]) %}
            {% for item in prices %}
              {% set price = item.get('price') %}
              {% if price is not none and avg > 0 %}
                {% set pct = (price / avg * 100) | float(0) %}
                {% if pct < 60 %}
                  {% set level = 'VERY_CHEAP' %}
                {% elif pct <= 90 %}
                  {% set level = 'CHEAP' %}
                {% elif pct < 115 %}
                  {% set level = 'NORMAL' %}
                {% elif pct < 140 %}
                  {% set level = 'EXPENSIVE' %}
                {% else %}
                  {% set level = 'VERY_EXPENSIVE' %}
                {% endif %}
                {% set entry = {'total': price | round(4), 'level': level} %}
                {% set ns.result = ns.result + [entry] %}
              {% endif %}
            {% endfor %}
            {{ ns.result }}
          unit_of_measurement: "EUR/kWh"
      - name: "WattWise Battery Charge from Solar"
        unique_id: "wattwise_battery_charge_from_solar"
        unit_of_measurement: "kW"
        state_class: "measurement"
        device_class: "power"
        icon: "mdi:solar-power"
        state: "{{ 0 }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Battery Charge from Grid"
        unique_id: "wattwise_battery_charge_from_grid"
        unit_of_measurement: "kW"
        state_class: "measurement"
        device_class: "power"
        icon: "mdi:transmission-tower"
        state: "{{ 0 }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Battery Discharge"
        unique_id: "wattwise_battery_discharge"
        unit_of_measurement: "kW"
        state_class: "measurement"
        device_class: "power"
        icon: "mdi:battery-outline"
        state: "{{ 0 }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Maximum Discharge Possible"
        unique_id: "wattwise_maximum_discharge_possible"
        unit_of_measurement: "kW"
        state_class: "measurement"
        device_class: "power"
        icon: "mdi:battery-minus-outline"
        state: "{{ 0 }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Grid Export"
        unique_id: "wattwise_grid_export"
        unit_of_measurement: "kW"
        state_class: "measurement"
        device_class: "power"
        icon: "mdi:export"
        state: "{{ 0 }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Grid Import"
        unique_id: "wattwise_grid_import"
        unit_of_measurement: "kW"
        state_class: "measurement"
        device_class: "power"
        icon: "mdi:import"
        state: "{{ 0 }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise State of Charge"
        unique_id: "wattwise_state_of_charge"
        unit_of_measurement: "kWh"
        state_class: "measurement"
        device_class: "battery"
        icon: "mdi:battery"
        state: "{{ 0 }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise State of Charge Percentage"
        unique_id: "wattwise_state_of_charge_percentage"
        unit_of_measurement: "%"
        state_class: "measurement"
        device_class: "battery"
        icon: "mdi:battery"
        state: "{{ 0 }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Consumption Forecast"
        unique_id: "wattwise_consumption_forecast"
        unit_of_measurement: "kW"
        state_class: "measurement"
        device_class: "power"
        icon: "mdi:home"
        state: "{{ 0 }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Solar Production Forecast"
        unique_id: "wattwise_solar_production_forecast"
        unit_of_measurement: "kW"
        state_class: "measurement"
        device_class: "power"
        icon: "mdi:weather-sunny"
        state: "{{ 0 }}"
        attributes:
          forecast: "{{ [] }}"

      - name: "WattWise Forecast Horizon"
        unique_id: "wattwise_forecast_horizon"
        unit_of_measurement: "h"
        state_class: "measurement"
        icon: "mdi:clock"
        state: "{{ 0 }}"

      - name: "WattWise Battery Charge Grid Session"
        unique_id: "wattwise_battery_charge_grid_session"
        unit_of_measurement: "kWh"
        state_class: "total"
        device_class: "energy"
        icon: "mdi:battery-charging-high"
        state: "{{ 0 }}"
        attributes:
          session_start: "{{ none }}"
          session_duration: "{{ 0 }}"

  - binary_sensor:
      - name: "WattWise Battery Charging from Grid"
        unique_id: "wattwise_battery_charging_from_grid"
        device_class: power
        icon: "mdi:battery-charging"
        state: "{{ off }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Battery Discharging Enabled"
        unique_id: "wattwise_battery_discharging_enabled"
        device_class: power
        icon: "mdi:battery-minus"
        state: "{{ off }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Battery Full Charge Status"
        unique_id: "wattwise_battery_full_charge_status"
        icon: "mdi:battery-charging-100"
        state: "{{ 0 }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Within cheapest hour"
        unique_id: "wattwise_within_cheapest_hour"
        icon: "mdi:clock-time-one-outline"
        state: "{{ off }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Within cheapest 2 hours"
        unique_id: "wattwise_within_cheapest_2_hours"
        icon: "mdi:clock-time-two-outline"
        state: "{{ off }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Within cheapest 3 hours"
        unique_id: "wattwise_within_cheapest_3_hours"
        icon: "mdi:clock-time-three-outline"
        state: "{{ off }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Within cheapest 4 hours"
        unique_id: "wattwise_within_cheapest_4_hours"
        icon: "mdi:clock-time-four-outline"
        state: "{{ off }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Within cheapest 5 hours"
        unique_id: "wattwise_within_cheapest_5_hours"
        icon: "mdi:clock-time-five-outline"
        state: "{{ off }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Within cheapest 6 hours"
        unique_id: "wattwise_within_cheapest_6_hours"
        icon: "mdi:clock-time-six-outline"
        state: "{{ off }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Within cheapest 7 hours"
        unique_id: "wattwise_within_cheapest_7_hours"
        icon: "mdi:clock-time-seven-outline"
        state: "{{ off }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Within cheapest 8 hours"
        unique_id: "wattwise_within_cheapest_8_hours"
        icon: "mdi:clock-time-eight-outline"
        state: "{{ off }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Within most expensive hour"
        unique_id: "wattwise_within_most_expensive_hour"
        icon: "mdi:clock-time-one-outline"
        state: "{{ off }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Within most expensive 2 hours"
        unique_id: "wattwise_within_most_expensive_2_hours"
        icon: "mdi:clock-time-two-outline"
        state: "{{ off }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Within most expensive 3 hours"
        unique_id: "wattwise_within_most_expensive_3_hours"
        icon: "mdi:clock-time-three-outline"
        state: "{{ off }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Within most expensive 4 hours"
        unique_id: "wattwise_within_most_expensive_4_hours"
        icon: "mdi:clock-time-four-outline"
        state: "{{ off }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Within most expensive 5 hours"
        unique_id: "wattwise_within_most_expensive_5_hours"
        icon: "mdi:clock-time-five-outline"
        state: "{{ off }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Within most expensive 6 hours"
        unique_id: "wattwise_within_most_expensive_6_hours"
        icon: "mdi:clock-time-six-outline"
        state: "{{ off }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Within most expensive 7 hours"
        unique_id: "wattwise_within_most_expensive_7_hours"
        icon: "mdi:clock-time-seven-outline"
        state: "{{ off }}"
        attributes:
          forecast: "{{ [] }}"
      - name: "WattWise Within most expensive 8 hours"
        unique_id: "wattwise_within_most_expensive_8_hours"
        icon: "mdi:clock-time-eight-outline"
        state: "{{ off }}"
        attributes:
          forecast: "{{ [] }}"
